### ISSUE TITLE
Rift using the gradle-all file instead of just binary package

### ISSUE THREAD

**Issue by UpcraftLP** [DimensionalDevelopment/Rift#15]
The gradle wrapper for rift uses the `-all` gradle installation, which is a lot larger than the binary distribution because of included sources and gradle documentation.
https://github.com/DimensionalDevelopment/Rift/blob/48ad23ca7194c9fc161390dc3c4da24717ce568a/gradle/wrapper/gradle-wrapper.properties#L5
the version should be changed to `-bin` instead of `all`.
see https://docs.gradle.org/current/userguide/gradle_wrapper.html for the difference.

To fix this, simply run the gradle wrapper task with the following argument:
`wrapper --distribution-type bin`

**Comment by Runemoro** [comment]
This is intentional, so that we get the gradle sources and docs in the IDE... This way we can use Ctrl-Q to get docs for any gradle task we're using, and Ctrl-Click to jump to its source. According to your logic, we should make gradle not download any sources for any of the libraries we're using.

**Comment by Runemoro** [comment]
Maybe it's pointless to you, because you don't need to edit Rift's build.gradle. I don't want to have to look up the gradle docs every time I want to do something in gradle. Pressing Ctrl-Q allows me to quickly see the documentation for any feature I need in build.gradle:

![a](https://user-images.githubusercontent.com/2412762/44006572-aaf714c6-9e54-11e8-88b0-d9a26f82ced1.png)

The gradle sources are downloaded just once for version 4.9 and will be reused for every other project.

**Comment by vtesterlwg** [comment]
figure out a way to change it yourself on your own system, but don't distrubute a build.gradle doing gradle-all. maybe make it a config option. or just commit `distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-bin.zip` in gradlew.properties but have it -all in your personal filesystem.
