### ISSUE TITLE
additional field

### ISSUE THREAD

**Issue by snajperro** [DimensionalDevelopment/Rift#34]
Could you add field "jar ":"1.13"
we need the field in version.json , because in our version of the launcher we must have this field!
"id": "1.13-rift-1.0.4-64",
  "inheritsFrom": "1.13",
  "jar": "1.13",
jar(field) - it has same value like inheritsFrom!

**Comment by UpcraftLP** [comment]
what do you mean "your version of the launcher"? use the official launcher.

**Comment by Robijnvogel** [comment]
You could start by telling us what launcher you are actually using. 😃

**Comment by UpcraftLP** [comment]
yeah, what launcher is it, and why can't the launcher understand vanilla profiles? Imo THAT should be changed, or do you want Mojang to implement this, as well?

**Comment by ZombieHDGaming** [comment]
@snajperro 1) Please change your launcher, you shouldn't use anything besides the official launcher or MultiMC, 2) If there is no need to add this field, we will not add it since you are the only person to mention anything like this thus far, and 3) What do you mean its the same with the Forge config? I just looked through the Forge config and saw nothing to what you are suggesting here.

And no, as a result, it will not improve the quality of the modloader. We are literally working with some of the best modders around, and NONE have suggested anything like this and would most likely remove it anyway since there is no official need for it in the normal launcher or with MultiMC.

**Comment by snajperro** [comment]
1)download the forge forge-1.12.2-14.23.4.2758-universal, example
2)unzip 
3)see file version.json

`  "id": "1.12.2-forge1.12.2-14.23.4.2758",
  "time": "2018-08-22T20:42:34+0000",
  "releaseTime": "1960-01-01T00:00:00-0700",
  "type": "release",
  "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge",
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "inheritsFrom": "1.12.2",
  "jar": "1.12.2",
  "logging": {},
  "libraries": [`

this field   "jar": "1.12.2",

**Comment by onDee** [comment]
Okay, you're asking to suport hacked launcher, i understand correctly?

**Comment by Robijnvogel** [comment]
Yeeeeeep, not going to happen 😄
