### ISSUE TITLE
[Feature Request] Can Rift add TweakClass for CoreMod like LiteLoader and Forge?

### ISSUE THREAD

**Issue by xfl03** [DimensionalDevelopment/Rift#4]
## Feature
If a Mod has "TweakClass" in its METAINF, it means the mod wants to use the TweakClass provided.  
Can Rift add TweakClass to LaunchWrapper for CoreMod like LiteLoader and Forge?  
Thanks a lot.
## Implements
- LiteLoader http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/main/java/com/mumfrey/liteloader/core/LiteLoaderEnumerator.java#L607
- Forge https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java#L394-L403

**Comment by Runemoro** [comment]
This can be done in Rift by creating a class that implements `InitializationListener`. From there, mods can add class transformers and tweakers by calling LaunchWrapper's methods.

Once we switch to ModLauncher, though, tweak classes will be loaded as services by ModLauncher, so they will just need to register their tweak class as a service by adding it to `META-INF/services`.

**Comment by xfl03** [comment]
I think it is meaningful to implement this feature in Rift directly.  
Forge and LiteLoader both implement it, which means it could be a universal way to register TweakClass in ModLoader.

**Comment by Runemoro** [comment]
It would, yes, but we will be switching to ModLauncher very soon which won't support IClassTransformers anymore. ModLauncher will have a universal way to register them (META-INF/services) which will be supported by Rift.

**Comment by xfl03** [comment]
ModLauncher cannot work now and there is no change in 24 days.
In my view, it still has a long time to switch to ModLauncher, why not support this feature to wait for the release of ModLauncher?

Thanks a lot!

**Comment by xfl03** [comment]
I made this feature by myself :(
https://github.com/xfl03/RiftTweakLoader

**Comment by Runemoro** [comment]
This is not done for Optifine. Optifine's TweakClass is ignored as it would only works with Forge. We're creating a custom tweaker and InitializationListener to set it up instead.

Using the TweakClass of a mod would cause several problems:
 - There's no way of checking they're for the right Minecraft version. 1.12 mods would also be loaded.
 - There's no way of checking they're meant for Rift. Some CurseForge mods claim they're for 1.13, but they expect srg names at runtime. They're meant to work with Forge 1.13 (though they won't since TweakClass will be replaced with meta-inf/service files when forge switches to ModLauncher in 1.13).

**Comment by xfl03** [comment]
> There's no way of checking they're for the right Minecraft version. 1.12 mods would also be loaded.

If I put 1.12.2 OptiFine into mods, it also will be loaded and cause a crash.

Users should take effort to put a jar file into mods folder rather than mod loader detect all thing for users.
